// database.js
// Berisi database kosakata statis bawaan aplikasi

const databaseKosakata = {
    "Kata Kerja": [
        // Level 1: Kebutuhan Dasar & Rutinitas Utama
        { kata: "mandi", level: 1 },
        { kata: "makan pagi", level: 1 },
        { kata: "makan siang", level: 1 },
        { kata: "makan malam", level: 1 },
        { kata: "tidur", level: 1 },
        { kata: "bangun tidur", level: 1 },
        { kata: "pipis", level: 1 },
        { kata: "eek/bab", level: 1 },
        { kata: "lepas celana", level: 1 },
        { kata: "pakai celana", level: 1 },
        { kata: "lepas baju", level: 1 },
        { kata: "pakai baju", level: 1 },
        { kata: "cuci tangan", level: 1 },
        
        // Level 2: Rutinitas, Tugas Sederhana & Bermain
        { kata: "gosok gigi", level: 2 },
        { kata: "keramas", level: 2 },
        { kata: "sekolah", level: 2 },
        { kata: "belajar", level: 2 },
        { kata: "bermain", level: 2 },
        { kata: "lihat TV", level: 2 },
        { kata: "sholat", level: 2 },
        { kata: "mengaji", level: 2 },
        { kata: "bereskan mainan", level: 2 },
        { kata: "buang sampah", level: 2 },
        { kata: "pulang sekolah", level: 2 },
        { kata: "belanja", level: 2 },
        { kata: "menggambar", level: 2 },
        { kata: "mewarnai", level: 2 },
        { kata: "jalan-jalan", level: 2 },
        { kata: "bersepeda", level: 2 },
        { kata: "bersantai", level: 2 },
        { kata: "olahraga", level: 2 },
        { kata: "bernyanyi", level: 2 },
        { kata: "beli jajan", level: 2 },

        // Level 3: Aktivitas Spesifik, Hobi & Tugas Kompleks
        { kata: "bereskan tempat tidur", level: 3 },
        { kata: "cuci baju", level: 3 },
        { kata: "cuci piring", level: 3 },
        { kata: "menyapu", level: 3 },
        { kata: "mengepel lantai", level: 3 },
        { kata: "siram bunga", level: 3 },
        { kata: "menanam", level: 3 },
        { kata: "jemur baju", level: 3 },
        { kata: "melipat baju", level: 3 },
        { kata: "menata baju", level: 3 },
        { kata: "setrika baju", level: 3 },
        { kata: "kancing baju", level: 3 },
        { kata: "lepas kancing baju", level: 3 },
        { kata: "cuci sepeda", level: 3 },
        { kata: "sikat sepatu", level: 3 },
        { kata: "membersihkan kaca", level: 3 },
        { kata: "memilah sampah", level: 3 },
        { kata: "kerja bakti dilingkungan rumah", level: 3 },
        { kata: "belajar di sekolah", level: 3 },
        { kata: "bermain dengan teman", level: 3 },
        { kata: "belajar kelompok", level: 3 },
        { kata: "menyiapkan keperluan sekolah", level: 3 },
        { kata: "membaca buku cerita", level: 3 },
        { kata: "menulis", level: 3 },
        { kata: "menghfal doa sehari-hari", level: 3 },
        { kata: "main piano", level: 3 },
        { kata: "main angklung", level: 3 },
        { kata: "berenang", level: 3 },
        { kata: "senam", level: 3 },
        { kata: "silat", level: 3 },
        { kata: "bermain kelereng", level: 3 },
        { kata: "bermain layang-layang", level: 3 },
        { kata: "potong rambut", level: 3 },
        { kata: "potong kuku", level: 3 },
        { kata: "memberi makan hewan", level: 3 },
        { kata: "beli bensin", level: 3 },
        { kata: "masak", level: 3 },
        { kata: "menata meja makan", level: 3 },
        { kata: "cuci sayur", level: 3 },
        { kata: "petik sayur", level: 3 },
        { kata: "potong sayur", level: 3 },
        { kata: "potong buah", level: 3 },
        { kata: "kupas kulit buah", level: 3 },
        { kata: "kupas bawang", level: 3 },
        { kata: "kupas telur rebus", level: 3 },
        { kata: "potong roti", level: 3 },
        { kata: "sisir rambut", level: 3 },
        { kata: "membuat tempe goreng", level: 3 },
        { kata: "membuat tahu goreng", level: 3 },
        { kata: "membuat jelly", level: 3 },
        { kata: "membuat nasi goreng", level: 3 },
        { kata: "membuat telur rebus", level: 3 },
        { kata: "membuat telur goreng", level: 3 },
        { kata: "membuat roti bakar", level: 3 },
        { kata: "membuat mie goreng", level: 3 },
        { kata: "membuat jus", level: 3 },
        { kata: "membuat susu", level: 3 },
        { kata: "membuat teh", level: 3 },
        { kata: "membuat kopi", level: 3 }
    ],

    "Kata Benda": [
        // Level 1: Benda Pakaian & Tubuh
        { kata: "baju", level: 1 },
        { kata: "celana", level: 1 },
        { kata: "rambut", level: 1 },
        { kata: "gigi", level: 1 },
        { kata: "tangan", level: 1 },

        // Level 2: Benda Sekitar & Permainan
        { kata: "mainan", level: 2 },
        { kata: "buku", level: 2 },
        { kata: "TV", level: 2 },
        { kata: "sepatu", level: 2 },
        { kata: "sepeda", level: 2 },
        { kata: "sampah", level: 2 },
        { kata: "tutup pintu", level: 2 },
        { kata: "tutup botol", level: 2 },
        { kata: "buka pintu", level: 2 },
        { kata: "buka botol", level: 2 },

        // Level 3: Benda Rumah Tangga & Hobi
        { kata: "piring", level: 3 },
        { kata: "kaca", level: 3 },
        { kata: "kancing baju", level: 3 },
        { kata: "kuku", level: 3 },
        { kata: "buku cerita", level: 3 },
        { kata: "piano", level: 3 },
        { kata: "angklung", level: 3 },
        { kata: "kelereng", level: 3 },
        { kata: "layang-layang", level: 3 },
        { kata: "lantai", level: 3 },
        { kata: "meja makan", level: 3 },
        { kata: "hewan", level: 3 },
        { kata: "bunga", level: 3 },
        { kata: "bensin", level: 3 }
    ],

    "Makanan": [
        // Level 1: Makanan & Minuman Dasar
        { kata: "susu", level: 1 },
        { kata: "air putih", level: 1 },
        { kata: "nasi", level: 1 },
        
        // Level 2: Lauk, Buah & Jajanan
        { kata: "buah", level: 2 },
        { kata: "sayur", level: 2 },
        { kata: "telur goreng", level: 2 },
        { kata: "telur rebus", level: 2 },
        { kata: "roti", level: 2 },
        { kata: "jajan", level: 2 },
        { kata: "jelly", level: 2 },
        { kata: "jus", level: 2 },
        
        // Level 3: Lauk Variasi & Minuman Lain
        { kata: "nasi goreng", level: 3 },
        { kata: "mie goreng", level: 3 },
        { kata: "tempe goreng", level: 3 },
        { kata: "tahu goreng", level: 3 },
        { kata: "kentang goreng", level: 3 },
        { kata: "roti bakar", level: 3 },
        { kata: "bawang", level: 3 },
        { kata: "teh", level: 3 },
        { kata: "kopi", level: 3 }
    ],

    "Tempat": [
        { kata: "pergi ke taman", level: 2 },
        { kata: "pergi ke Playground", level: 2 },
        { kata: "pergi ke pantai", level: 2 }
    ],

    "Waktu": [
        // Hari
        { kata: "hari senin", level: 2 },
        { kata: "hari selasa", level: 2 },
        { kata: "hari rabu", level: 2 },
        { kata: "hari kamis", level: 2 },
        { kata: "hari jum'at", level: 2 },
        { kata: "hari sabtu", level: 2 },
        { kata: "hari minggu", level: 2 },
        // Keterangan
        { kata: "kemarin", level: 2 },
        { kata: "sore hari", level: 2 },
        // Bulan
        { kata: "Januari", level: 3 },
        { kata: "Februari", level: 3 },
        { kata: "Maret", level: 3 },
        { kata: "April", level: 3 },
        { kata: "Mei", level: 3 },
        { kata: "Juni", level: 3 },
        { kata: "Juli", level: 3 },
        { kata: "Agustus", level: 3 },
        { kata: "September", level: 3 },
        { kata: "Oktober", level: 3 },
        { kata: "November", level: 3 },
        { kata: "Desember", level: 3 }
    ]
};
