const kataKerja = [];
// Struktur Data sesuai list SRS
export const kataKerjaDb = [
    { id: "kk_1", text: "bangun tidur", category: "kata-kerja", level: 1, image: "", voice: "", hidden: false, custom: false },
    { id: "kk_2", text: "bereskan tempat tidur", category: "kata-kerja", level: 2, image: "", voice: "", hidden: false, custom: false },
    { id: "kk_3", text: "mandi", category: "kata-kerja", level: 1, image: "", voice: "", hidden: false, custom: false },
    { id: "kk_4", text: "gosok gigi", category: "kata-kerja", level: 1, image: "", voice: "", hidden: false, custom: false },
    { id: "kk_5", text: "makan pagi", category: "kata-kerja", level: 1, image: "", voice: "", hidden: false, custom: false },
    { id: "kk_6", text: "sekolah", category: "kata-kerja", level: 1, image: "", voice: "", hidden: false, custom: false },
    // Anda bisa melanjutkan paste sisa daftar ke array ini sesuai urutan list SRS.
    { id: "kk_last", text: "menyiapkan keperluan sekolah", category: "kata-kerja", level: 3, image: "", voice: "", hidden: false, custom: false }
];
// File: database/kata-kerja.js

const daftarKataKerja = [
    // Level 1: Kebutuhan dasar, *primary reinforcer*, dan rutinitas fundamental
    { text: "bangun tidur", level: 1 },
    { text: "mandi", level: 1 },
    { text: "gosok gigi", level: 1 },
    { text: "makan pagi", level: 1 },
    { text: "makan siang", level: 1 },
    { text: "makan malam", level: 1 },
    { text: "tidur", level: 1 },
    { text: "cuci tangan", level: 1 },
    { text: "pipis", level: 1 },
    { text: "BAB", level: 1 },

    // Level 2: Aktivitas tunggal sederhana, bina diri dasar, dan bermain
    { text: "bermain", level: 2 },
    { text: "lihat TV", level: 2 },
    { text: "lepas celana", level: 2 },
    { text: "pakai celana", level: 2 },
    { text: "lepas baju", level: 2 },
    { text: "pakai baju", level: 2 },
    { text: "sisir rambut", level: 2 },
    { text: "buang sampah", level: 2 },
    { text: "bersantai", level: 2 },
    { text: "jalan-jalan", level: 2 },
    { text: "olahraga", level: 2 },
    { text: "bernyanyi", level: 2 },
    { text: "menggambar", level: 2 },
    { text: "mewarnai", level: 2 },

    // Level 3: Tugas harian spesifik, rutinitas sekolah, dan sosial
    { text: "bereskan tempat tidur", level: 3 },
    { text: "sekolah", level: 3 },
    { text: "bermain dengan teman", level: 3 },
    { text: "belajar di sekolah", level: 3 },
    { text: "pulang sekolah", level: 3 },
    { text: "sholat", level: 3 },
    { text: "mengaji", level: 3 },
    { text: "belajar", level: 3 },
    { text: "menyapu", level: 3 },
    { text: "siram bunga", level: 3 },
    { text: "jemur baju", level: 3 },
    { text: "melipat baju", level: 3 },
    { text: "menata baju", level: 3 },
    { text: "main piano", level: 3 },
    { text: "main angklung", level: 3 },
    { text: "berenang", level: 3 },
    { text: "senam", level: 3 },
    { text: "cuci sepeda", level: 3 },
    { text: "keramas", level: 3 },
    { text: "kancing baju", level: 3 },
    { text: "lepas kancing baju", level: 3 },
    { text: "sikat sepatu", level: 3 },
    { text: "menulis", level: 3 },
    { text: "silat", level: 3 },
    { text: "bermain kelereng", level: 3 },
    { text: "bermain layang-layang", level: 3 },
    { text: "menata meja makan", level: 3 },
    { text: "memberi makan hewan", level: 3 },
    { text: "membaca buku cerita", level: 3 },
    { text: "potong rambut", level: 3 },
    { text: "potong kuku", level: 3 },
    { text: "beli jajan", level: 3 },
    { text: "belanja", level: 3 },
    { text: "bersepeda", level: 3 },
    { text: "menanam", level: 3 },
    { text: "membersihkan kaca", level: 3 },
    { text: "cuci sayur", level: 3 },
    { text: "bereskan mainan", level: 3 },
    { text: "menyiapkan keperluan sekolah", level: 3 },
    { text: "belajar kelompok", level: 3 },

    // Level 4: Aktivitas multi-step yang membutuhkan sequencing (memasak, meracik, dll)
    { text: "cuci baju", level: 4 },
    { text: "cuci piring", level: 4 },
    { text: "mengepel lantai", level: 4 },
    { text: "mengepel", level: 4 },
    { text: "setrika baju", level: 4 },
    { text: "petik sayur", level: 4 },
    { text: "kupas telur rebus", level: 4 },
    { text: "kupas kulit buah", level: 4 },
    { text: "kupas bawang", level: 4 },
    { text: "potong buah", level: 4 },
    { text: "potong sayur", level: 4 },
    { text: "potong roti", level: 4 },
    { text: "membuat tempe goreng", level: 4 },
    { text: "membuat tahu goreng", level: 4 },
    { text: "membuat jelly", level: 4 },
    { text: "membuat nasi goreng", level: 4 },
    { text: "membuat telur rebus", level: 4 },
    { text: "membuat jus", level: 4 },
    { text: "membuat roti bakar", level: 4 },
    { text: "membuat telur goreng", level: 4 },
    { text: "membuat susu", level: 4 },
    { text: "membuat mi goreng", level: 4 },
    { text: "membuat teh", level: 4 },
    { text: "membuat kopi", level: 4 },
    { text: "masak", level: 4 },
    { text: "beli bensin", level: 4 },
    { text: "memilah sampah", level: 4 },
    { text: "menghafal doa sehari-hari", level: 4 },
    { text: "kerja bakti di lingkungan rumah", level: 4 }
];

export const kataKerjaDb = daftarKataKerja.map((item, index) => ({
    id: `kk_${index + 1}`,
    text: item.text,
    category: "kata-kerja",
    level: item.level,
    image: "",
    voice: "",
    hidden: false,
    custom: false
}));
     
